[build]
  command = "CI=false npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.0"
  CI = "false"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  framework = "#custom"
  functionsPort = 9000

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
